@startuml

class Funcionario {
    - nome: String
    - cpf: String
    - matricula: String
    - salario: double
    - departamento: Departamento
    - cargo: Cargo
    - dataCadastro: Date
    - dataDemissao: Date
    - funcionarios: ArrayList<Funcionario>
    - matriculasCount: Map<String, Integer>
    - formatter: SimpleDateFormat

    + Funcionario(String, String, double, Departamento, Cargo, Date)
    + popularFuncionarios(): void
    + setDepartamento(Departamento): void
    + getSalario(): double
    + getNome(): String
    + getDataCadastro(): String
    + getDataDemissao(): String
    + getFuncsByDep(Departamento): ArrayList<Funcionario>
    + getFuncionarioByIndex(int): Funcionario
    + getMatricula(): String
    + addNewFuncionario(Funcionario): void
    + removeFuncionario(Funcionario): void
    + getCargo(): Cargo
    + getDepartamento(): Departamento
    + getFuncionarios(): ArrayList<Funcionario>
    + formatarData(Date): String
    + generateMatricula(): String
}
@enduml